env JWT_SECRET;
pcre_jit on;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # Using the Docker container names for the internal networks
    upstream auth_service {
        server auth_service:5500; 
    }

    upstream backend_service {
        server backend_service:8080; 
    }

    client_body_temp_path /var/run/openresty/nginx-client-body;
    proxy_temp_path       /var/run/openresty/nginx-proxy;
    fastcgi_temp_path     /var/run/openresty/nginx-fastcgi;
    uwsgi_temp_path       /var/run/openresty/nginx-uwsgi;
    scgi_temp_path        /var/run/openresty/nginx-scgi;

    sendfile        on;
    keepalive_timeout  65;

    # OpenResty's default config includes a dummy server block that causes duplicate errors.

    # include /etc/nginx/conf.d/*.conf; 

    # Defined ONCE, globally inside the http block
    lua_package_path '/usr/local/openresty/nginx/lua/?.lua;;';

    server {
        # Nginx listens on 80 internally (Docker maps 8080 to this externally)
        listen 80;
        
        location / {
            access_by_lua_file /usr/local/openresty/nginx/lua/main.lua;
            proxy_pass http://backend_service;
        }
    }
}